### ISSUE TITLE
`FabricBlockSettings` missing some methods

### ISSUE THREAD

**Issue by EthanRStokes** [QuiltMC/quilted-fabric-api#102]
In QFAPI 7.0.1, `FabricBlockSettings` is missing the `pistonBehavior()` and `instrument()` methods found in Fabric API and in QSL's `QuiltBlockSettings`

This causes a compatibility issue with mods that use these methods and crashes on startup. An example is this crash with the Wilder Wild mod: https://mclo.gs/KExZ9lJ

**Comment by EnnuiL** [comment]
dear god, there was quite the gap on `FabricBlockSettings`; I've reinstated it and will hopefully ship with QFAPI 7.0.2

**Comment by EnnuiL** [comment]
Fixed with QFAPI 7.0.2
