### ISSUE TITLE
Problems loading embeded libraries

### ISSUE THREAD

**Issue by quiqueck** [QuiltMC/quilted-fabric-api#103]
Sorry for the bother, but I just got a report from a user that looks like QFAPI is not loading an embeded library from our mod. The original issue is here: quiqueck/BCLib#97

BCLib include another utility library, that provides some ui-components. The Mod-Listing on the bottom of that report does not include the embeded lib. So for me, this looks as if the libarry is not loaded.

I am not sure if this is something I did worng, or if it (probably not) an issue with QFAPI. So any help/hint would be greatly appreciated.

**Comment by AlexIIL** [comment]
This is likely related to [quilt loader](https://github.com/QuiltMC/quilt-loader), and not quilted-fabric-api (loader is responsible for actually loading mods).

**Comment by EnnuiL** [comment]
Yep, this doesn't seem like this is within my (well, our (QFAPI team) :p) territory; I'll transfer this issue to the Quilt Loader repo
EDIT: welp, I don't have the permission to do that

**Comment by quiqueck** [comment]
Oh, I am sorry. 
And many thanks for transferring it to the right, and the fast replies. :)
