### ISSUE TITLE
Exordium and memoryleakfix issues with quilt (Internal Error)

### ISSUE THREAD

**Issue by ShadowTigerCool** [QuiltMC/quilted-fabric-api#104]

**Comment by Fnige** [comment]
Do you have a crash log?

**Comment by shadowtigercool** [comment]
[crash-2023-06-21_08.06.50.7891-quilt_loader.txt](https://github.com/QuiltMC/quilted-fabric-api/files/11817324/crash-2023-06-21_08.06.50.7891-quilt_loader.txt)

**Comment by shadowtigercool** [comment]
happens on both 1.19.4 and 1.20.1

**Comment by shadowtigercool** [comment]
here's the crash logs
[crash-2023-06-21_08.06.50.7891-quilt_loader.txt](https://github.com/QuiltMC/quilted-fabric-api/files/11817324/crash-2023-06-21_08.06.50.7891-quilt_loader.txt)
https://pastebin.com/GqfCDgN6

**Comment by shadowtigercool** [comment]
**https://github.com/LlamaLad7/MixinExtras/issues/33**

https://github.com/QuiltMC/quilt-loader/issues/315
