### ISSUE TITLE
[1.20.1] Datapack Structure causes watchdog timeout?

### ISSUE THREAD

**Issue by generrosity** [QuiltMC/quilted-fabric-api#107]
Hi! Appologies as newbie, I've put packs together but not specifically used Quilt before, but assisting with trying to track down a Bug.

I didn't realize 'Dungeons and Taverns' was a datapack until we started investigating, and took a while to find a location to actually communicate with the creators.
-> https://modrinth.com/datapack/dungeons-and-taverns/versions
-> https://www.planetminecraft.com/data-pack/nova-structures

Steps to recreate: 
* For Curseforge: Create new profile, Fabric, add only dungeons-and-taverns.
* For Prism: Create new profiles, Quilt, add only dungeons-and-taverns.
* Seed: -6808035261700636515 as creative
* Go directly to the nether in spectator mode (/execute in minecraft:nether run tp generrosity 0 100 0) 
* immediately it has loaded 91 blocks in each direction. I can happily fly around and see this in journeymap etc, its about 4 minutes before Quilt throws the error. Fabric is quite happy to generate further.
* Watchdog alert that process were long running 'server tick taken 121088'.

Thanks for having a look - is there any other diagnostics we could try? Is there known issues or blanket incompatabilities with datapack structures? (other overworld parts of this datapack are working marvelously well, just the nether stronghold it creates)

**Comment by EnnuiL** [comment]
Hm, this is possibly related to issue #109 (or a duplicate of something newer, what a paradox! :p);
Does adding this fixed-up Quilt Biomes API jar fix the issue for you?
https://cdn.discordapp.com/attachments/1104017054325026877/1134721192989835415/biome-6.0.41.20.1-adjusted.jar

**Comment by generrosity** [comment]
Thanks for the follow up!

We finally figured out there were mod interactions going on, specifically with Waystone, and Blay has since fixed (or significantly reduced) the overall structure slowness.
