### ISSUE TITLE
Missing `MixinCreativePlayerInventoryGui` in item groups

### ISSUE THREAD

**Issue by triphora** [QuiltMC/quilted-fabric-api#11]
See Earthcomputer/clientcommands#396

This should be fixed on our end like #10

**Comment by triphora** [comment]
Yeah, this isn't going to be possible for us to fix.

It's not a matter of a simple class/field not found -- it takes the `fabric_currentPage` field in the transformed jar, makes it accessible via reflection, and sets it to zero when any of its own client-sided item groups are deleted -- which means it isn't really possible for us to do this.

If anyone looking at this wants to PR/implement a fix in CC, it's a matter of checking whether `quilt$currentPage` is there instead of `fabric_currentPage`.

**Comment by Patbox** [comment]
Ideally no one should assume stability of this name and should just try catch it anyway. Throug official api for that would be also good idea
