### ISSUE TITLE
Quilted Crashes even when its only the QFAPI

### ISSUE THREAD

**Issue by NotSoNitro** [QuiltMC/quilted-fabric-api#110]
I always get this crash when loading up quilted on the latest version of the QFAPI, there are no mods even installed on the MC instance and i have no idea what is causing this
![image](https://github.com/QuiltMC/quilted-fabric-api/assets/50882775/758ae0be-7b39-42a4-8b5a-0658eee89923)
idk if this is a problem with my MC folder or the mod itself.

**Comment by eristhea** [comment]
looks like your Quilt Loader is a tad outdated (we're on `0.19.2` now), that should fix it! just reopen if you're still getting the error

**Comment by NotSoNitro** [comment]
that seems to have done it, thanks!
