### ISSUE TITLE
1.19.4 FAPI 0.86.1 backport?

### ISSUE THREAD

**Issue by meowinqq** [QuiltMC/quilted-fabric-api#114]
Two of my mods in particular (Indium and Continuity, both for 1.19.4, both endorse compatibility with Quilt) require the latest iteration of FAPI to launch. Is there any chance that FAPI 0.86.1 could be backported to QFAPI 1.19.4? I'm aware that integration for the most recent release of QFAPI was only released recently, so if such isn't possible as of now, I totally understand. Thank you for your time!

**Comment by rinOfTheStars** [comment]
Might be able to work on this in the next few days, but it'd require a backport of the latest QSL update as well

**Comment by rinOfTheStars** [comment]
Actually, maybe it wouldn't? Going to have to ask around to figure this out

**Comment by arschfidel0815** [comment]
Any news on this?

**Comment by rinOfTheStars** [comment]
Can now be closed as of #132 and its release!
