### ISSUE TITLE
RuntimeException: Mod qfapi-7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1.jar" has an invalid quilt.mod.json file!

### ISSUE THREAD

**Issue by evildudegghd** [QuiltMC/quilted-fabric-api#116]
Yes, so i got the issue that this file got an error by opening with the new Modrinth Launcher. What should i do? I tried downgrading the mod and it doesn't worked either.
[stdout.log](https://github.com/QuiltMC/quilted-fabric-api/files/12313562/stdout.log)

**Comment by OroArmor** [comment]
Make sure you are using the latest version of quilt loader. I believe you  need 0.19.2 or higher.

**Comment by evildudegghd** [comment]
I mean i used 1.20 and i tried all quilt versions of it

**Comment by Kevin230474** [comment]
![image](https://github.com/QuiltMC/quilted-fabric-api/assets/96561073/cdb805be-0689-4a80-82f7-28e1831f3527)

**Comment by OroArmor** [comment]
That's quilt loader 0.17.9. Please update the loader by reinstalling quilt from the installer

**Comment by evildudegghd** [comment]
it worked in the minecraft and curseforge launcher with the same version

**Comment by evildudegghd** [comment]
bruh, it really needed to be on the newest version, but thx
