### ISSUE TITLE
[1.19.2] Bring QFAPI up to Parity with Fabric API 0.76.1?

### ISSUE THREAD

**Issue by emoace** [QuiltMC/quilted-fabric-api#123]
On 1.19.2, a few mods that have been released more recently have used Fabric API 0.76.1 but QSL only has parity with Fabric API 0.76.0

**Comment by rinOfTheStars** [comment]
Now that 1.19.4 sync is done ill probably start work on this soonish—it's a _really_ small sync PR so it shouldn't take too long once I do start on it in a few days at the most

**Comment by Jakub-Wilk** [comment]
Any updates on this?

**Comment by TheGlitch76** [comment]
Released as QFAPI 4.0.0-beta.30 ([Modrinth](https://modrinth.com/mod/qsl/version/4.0.0-beta.30+0.77.0-1.19.2))
