### ISSUE TITLE
Fabric Renderer API should be updated

### ISSUE THREAD

**Issue by YSYavuzSelim** [QuiltMC/quilted-fabric-api#130]
![image](https://github.com/QuiltMC/quilted-fabric-api/assets/79472692/02a93697-9848-4d0c-b3e4-93ecb4693081)
Fabric-Renderer-api in 1.19.4 is at version 2.3.1 but the mod that I am using (Indium) needs 2.4.0

**Comment by YSYavuzSelim** [comment]
I am using the latest version of QFapi on 1.19.4

**Comment by Poopooracoocoo** [comment]
> I am using the latest version of QFapi on 1.19.4

... Define latest.

**Comment by rinOfTheStars** [comment]
This is a duplicate of https://github.com/QuiltMC/quilted-fabric-api/issues/123 and https://github.com/QuiltMC/quilted-fabric-api/issues/114

**Comment by rinOfTheStars** [comment]
Can now be closed as of #132
