### ISSUE TITLE
6.0.0-beta.10 for 1.19.4 does not load Model Loading API v1 in production

### ISSUE THREAD

**Issue by PepperCode1** [QuiltMC/quilted-fabric-api#138]
[QFAPI 6.0.0-beta.10 and QSL 5.0.0-beta.11 for 1.19.4](https://modrinth.com/mod/qsl/version/6.0.0-beta.10+0.87.0-1.19.4) (currently the latest version for 1.19.4 as of writing this) claims to include Model Loading API v1, which was added in Fabric API 0.87.0. However, this module is not loaded in a production environment, yet is present in a development environment. Thus, any 1.19.4 mods that use Model Loading API v1, such as Continuity, will crash without a clear error in a production environment. This implies that this QSL/QFAPI jar was not built correctly.

**Comment by rinOfTheStars** [comment]
@EnnuiL presumably you're taking a break rn (since you're not in the discords anymore) but when you have a chance, could you take a look at this, or at the very least ping whoever would be able to actually figure out what's wrong here? Kind of lost as to what to do w. this one.

**Comment by EnnuiL** [comment]
Issue is that the main QMJ wasn't updated in order to include the new libraries, that's what you need to fix
(also, that isn't a break)
