### ISSUE TITLE
Support for 1.20.4.

### ISSUE THREAD

**Issue by jacklollz2** [QuiltMC/quilted-fabric-api#142]
Fabric has had 1.20.4 for weeks now.

Is there any benefit to using Quilt, such as memory, or performance? Quilt just seems to be "Fabric" renamed to "Quilt".

If these updates will be this slow, I'll stick with Fabric, unless you can justify Quilt in any way.

**Comment by OroArmor** [comment]
Support for 1.20.4 is planned for. Work is still being done to release 1.20.2. As the maintainer for both QFAPI and QSL, I have been extremely busy and unable to spend any time on updates.

If you want to know the difference between quilt and fabric, check [our FAQ](https://quiltmc.org/en/about/faq/)

**Comment by FirstMegaGame4** [comment]
> Fabric has had 1.20.4 for weeks now.
> 
> Is there any benefit to using Quilt, such as memory, or performance? Quilt just seems to be "Fabric" renamed to "Quilt".
> 
> If these updates will be this slow, I'll stick with Fabric, unless you can justify Quilt in any way.

it's typically this kind of comment that destroys the desire of some developers to maintain their projects
please be understanding towards them

**Comment by FirstMegaGame4** [comment]
Quilt provides a lot of useful tools and is working on lot of more advanced projects than Fabric's one. There's a few examples:
- Quilt's Enigma, which recently got its 2.0 release.
- Collision Handling ASM, which will be really useful when ready-for-release.
- QSL, which provides new modules that are really usefulls for devs, such as Recipe API, Registry Entry Attributes, Registerable Tacked Data Handlers etc...
- Quilt Mappings which will enters to its 2.0 release in the future, allowing a lot of useful additions for mod developers.
- Quilt Loader, with their Quilt Loader Plugins and improvements over the Fabric Loader.

**Comment by jacklollz2** [comment]
> Support for 1.20.4 is planned for. Work is still being done to release 1.20.2. As the maintainer for both QFAPI and QSL, I have been extremely busy and unable to spend any time on updates.
> 
> If you want to know the difference between quilt and fabric, check [our FAQ](https://quiltmc.org/en/about/faq/)

I've read this useless FAQ many times, and all I see is: "More compatible", and "an inclusive community."
