### ISSUE TITLE
Support 1.20.4

### ISSUE THREAD

**Issue by mrmelon54** [QuiltMC/quilted-fabric-api#148]
The other 1.20.4 issue was closed as completed but I don't see any downloads on Modrinth thus I am opening this issue.

**Comment by jacklollz2** [comment]
I am experiencing this as well, I checked Modrinth and I do not see the 1.20.4 builds, even in beta. I don't understand why it was closed as completed.

**Comment by OroArmor** [comment]
Oops. That was my bad. I thought the issue was for 1.20.2.

**Comment by FirstMegaGame4** [comment]
new nightmare issue

**Comment by jacklollz2** [comment]
I wonder if 1.20.5 will come out before this does.

**Comment by mrmelon54** [comment]
I wouldn't be surprised, its been over 2 months since the first Fabric API for 1.20.4 released

**Comment by OroArmor** [comment]
Maybe, but only because I'm fixing up 1.20.2 before moving on to 1.20.3/4. That update is much easier though

**Comment by EthanZeigler** [comment]
It's been more than a month since 1.20.4 released and this is still an issue. What's going on?

**Comment by FirstMegaGame4** [comment]
It's going that Oro has a life and its school time is more important.

**Comment by EthanZeigler** [comment]
@FirstMegaGame4 don't get me wrong, I fully understand that and sympathize, but this is a core part of the quilt ecosystem. He really shouldn't be soloing the changes given the importance. I'd help myself but i'm not familiar with fabric's internals enough to do so.

**Comment by Cuteistfox** [comment]
adding `net.fabricmc.fabric.impl.networking.payload.` to the qfapi is also very unimportant

**Comment by OroArmor** [comment]
No. Mods should not be referencing that code. If you need to, ask fabric for an api.

**Comment by dhouck** [comment]
Also it seems off-topic even if you were to convince people that an `impl` package should be in the qfapi.

**Comment by Cuteistfox** [comment]
i meant to say unimportant, lol

**Comment by Cuteistfox** [comment]
but yeah this is off topic

**Comment by OroArmor** [comment]
https://github.com/QuiltMC/quilt-standard-libraries/commit/767263a209e4c44424a543b39e54fd2f983b32b9

**Comment by OroArmor** [comment]
Finished!
