### ISSUE TITLE
UpStream Sync for 1.20.1 => Including FAPI 0.92.0

### ISSUE THREAD

**Issue by FirstMegaGame4** [QuiltMC/quilted-fabric-api#149]
FAPI 0.92.0 was just released, and backported a few things like mob conversion event and more importantly the Data Attachment API.

I can't add the "upstream sync" label by myself, waiting on writer access holders for that.

**Comment by PolyframeX** [comment]
Numerous mods I use are starting to depend on 0.92.0 or higher, making a decent chunk of mods (such as botania, language reload, etc) not usable.

**Comment by ImBehinYa** [comment]
Yes please update, when can we expect?  0.92.0?
![image](https://github.com/QuiltMC/quilted-fabric-api/assets/63367722/24ecb6f8-1623-4145-97f3-1016b6b63880)

**Comment by TheGlitch76** [comment]
Closed by #163 and the subsequent release of QFAPI 7.5.0 ([Modrinth](https://modrinth.com/mod/qsl/version/7.5.0+0.92.2-1.20.1)) which provides FAPI 0.92.2
