### ISSUE TITLE
Crash while using the Axiom mod

### ISSUE THREAD

**Issue by Spiderach** [QuiltMC/quilted-fabric-api#151]
Tested with just QFAPI and Axiom installed with qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1. There are no missing dependencies, but with all the custom rendering and mixins that Axiom uses I'm not suprised it doesn't want to play nice.
[crash-2024-03-13_00.09.40-client.txt](https://github.com/QuiltMC/quilted-fabric-api/files/14582535/crash-2024-03-13_00.09.40-client.txt)

**Comment by OroArmor** [comment]
This is more of a loader issue. Not api. There are current no plans on how to fix the issue.
