### ISSUE TITLE
Legacy4J incompatibility

### ISSUE THREAD

**Issue by tiredtires** [QuiltMC/quilted-fabric-api#168]
Quilt version 0.26.3 for 1.20.1
Most recent version of quilted fabric api used.
It happens whether or not I use other mods. Legacy4j requires fabric api.
I've checked the issues page for legacy4j and they claim that it's quilted fabric api being incompatible. Heres the issue page in legacy4j: https://github.com/Wilyicaro/Legacy-Minecraft/issues/169
Heres a pastebin of the error report
https://pastebin.com/y0vQ140S

**Comment by OroArmor** [comment]
They use fabric internals: `net.fabricmc.fabric.impl.resource.loader.ResourceManagerHelperImpl.registerBuiltinResourcePack`.

From looking at the code, it seems they store a resource pack in their mod in a non-standard location, and are calling the implementation method to get around this. The method they should call is [this](https://github.com/FabricMC/fabric/blob/3ed6d97f7ca7d14da7607d107b82ba0d10598bb8/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/api/resource/ResourceManagerHelper.java#L99) and move their resource pack to the standardized location.
