### ISSUE TITLE
Potential incompatibillity in fabric-item-api-v1

### ISSUE THREAD

**Issue by FavoritoHJS** [QuiltMC/quilted-fabric-api#21]
This is probably the wrong place to report this, but here we go...

Seems like there's a regression on the `fabric-item-api-v1` module... which is weird because the current Quilted-FAPI version for 1.18.2 is based on a version after that got last changed. Maybe some parameter isn't being passed correctly?

see: AztechMC/Modern-Industrialization#276

**Comment by EnnuiL** [comment]
The issue is that Quilted FAPI had reimplemented Fabric's Item API on top of QSL's Item Settings API, however, while the Fabric-only parts had API support, they effectively weren't implemented. This issue will be sorted out soon

**Comment by FavoritoHJS** [comment]
Seems to be fixed in beta-21 according to Ennui. Closing.
