### ISSUE TITLE
Some modules don't have the client mixin config registered

### ISSUE THREAD

**Issue by BasiqueEvangelist** [QuiltMC/quilted-fabric-api#22]
For example, the upstream `fabric-object-builder-api-v1` module has [two configs](https://github.com/FabricMC/fabric/blob/1.19/fabric-object-builder-api-v1/src/main/resources/fabric.mod.json#L23-L29), one for common and one for client, while the quilted module [only has the common one registered](https://github.com/QuiltMC/quilted-fabric-api/blob/1.19/fabric-object-builder-api-v1/src/main/resources/quilt.mod.json#L34). This causes issues with mods using `FabricModelPredicateProviderRegistry`, as it uses an accessor that isn't registered (wisp-forest/numismatic-overhaul#26, wisp-forest/things#39)

**Comment by EnnuiL** [comment]
Solved since 1.0.0-beta.21 and 2.0.0-alpha.3
