### ISSUE TITLE
qfapi-4.0.0-beta.7_qsl-3.0.0-beta.10_fapi-0.59.0_mc-1.19.2 exports 0.58.0 but 0.59.0 expected

### ISSUE THREAD

**Issue by lospejos** [QuiltMC/quilted-fabric-api#29]
When starting mods requiring
```
"fabricloader": ">=0.14.9"
```
(f.e. `asteroid-1.3.0`)

in their `fabric.mod.json` with `qfapi-4.0.0-beta.7_qsl-3.0.0-beta.10_fapi-0.59.0_mc-1.19.2` I expected that QFAPI will export **0.59.0** loader version (as states from file name), but error appears:

```
Unhandled error involving mod 'Asteroid Rewritten' (asteroid) v1.3.0:
Dependency for mod 'asteroid' on fabricloader versions [>=0.14.9] (0 valid options, 1 invalid options)
    x provided mod 'fabricloader' version '0.14.8' from mod 'quilt_loader' version 0.17.2-beta.2 loaded from C:\games\...\libraries\org\quiltmc\quilt-loader\0.17.2-beta.2\quilt-loader-0.17.2-beta.2.jar
```

It seems that this QFAPI version exports **0.58.0** version.

Please assist. Thanks.

**Comment by Jamalam360** [comment]
Asteroid is wanting Fabric Loader, QFAPI provides Fabric API. Try updating Quilt Loader, but if that doesn't work you'll have to remove asteroid or wait for quilt loader to update

**Comment by lospejos** [comment]
Thanks for reply. Currently I removed `Asteroids` as it is not critical for me, waiting for quilt loader updates.
