### ISSUE TITLE
QLS 4.0.0 beta 10 crashed a Autoswitch 5.1.5

### ISSUE THREAD

**Issue by c1oudychan** [QuiltMC/quilted-fabric-api#33]
**MC** 1.19.2
**QSL** 4.0.0 beta 10
**[Autoswitch](https://modrinth.com/mod/autoswitch)** 5.1.5

Autoswitch started a version 5.1.5 get crashed(a older versions are working). Reported here: [dexman545/Fabric-Autoswitch#44](https://github.com/dexman545/Fabric-Autoswitch/issues/44) . Dev say: At this time, the only support quilt is getting is "I won't intentionally break it."

Logs: https://mclo.gs/dydqgZp

**Comment by EnnuiL** [comment]
Fixed on QFAPI 4.0.0-beta.11
