### ISSUE TITLE
MixinApplyError: Mixin [quilt_item_extension.mixins.json:bow.BowAttackMixin from mod quilt_item_extension] from phase [DEFAULT] in config [quilt_item_extension.mixins.json] FAILED during APPLY

### ISSUE THREAD

**Issue by lospejos** [QuiltMC/quilted-fabric-api#34]
It seems something is broken in recent `qfapi-4.0.0-beta.10_qsl-3.0.0-beta.15_fapi-0.60.0_mc-1.19.2`.

My mods:

`enhancedcraft-1.3.2`
`modmenu-4.0.6`
`qfapi-4.0.0-beta.10_qsl-3.0.0-beta.15_fapi-0.60.0_mc-1.19.2`

When starting, I got error:

```
Mixin apply for mod quilt_item_extension failed quilt_item_extension.mixins.json:bow.BowAttackMixin from mod quilt_item_extension -> net.minecraft.class_1547: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1547::modifyShotProjectile with priority 1000 cannot inject into net/minecraft/class_1547::method_7105(Lnet/minecraft/class_1309;F)V merged by com.spxctreofficial.enhancedcraft.mixin.entity.AbstractSkeletonEntityMixin with priority 1000 [PREINJECT Applicator Phase -> quilt_item_extension.mixins.json:bow.BowAttackMixin from mod quilt_item_extension -> Prepare Injections ->  -> redirect$zlg000$modifyShotProjectile(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_1309;F)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1547::modifyShotProjectile with priority 1000 cannot inject into net/minecraft/class_1547::method_7105(Lnet/minecraft/class_1309;F)V merged by com.spxctreofficial.enhancedcraft.mixin.entity.AbstractSkeletonEntityMixin with priority 1000 [PREINJECT Applicator Phase -> quilt_item_extension.mixins.json:bow.BowAttackMixin from mod quilt_item_extension -> Prepare Injections ->  -> redirect$zlg000$modifyShotProjectile(Lnet/minecraft/class_1937;Lnet/minecraft/class_1297;Lnet/minecraft/class_1309;F)Z -> Prepare]
```

Full log see here:
https://gist.github.com/lospejos/920a66559215d09c9da5785dcb47cd73

If I rollback to previous `QFAPI` version `qfapi-4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2` everything works just fine.

I'm not sure is it a `QFAPI` or `Enhanced Craft` mod error.

Please assist.
Thanks.

**Comment by Kroppeb** [comment]
It's a mod compatibility issue between enhancedcraft and the new bow api in qsl

**Comment by lospejos** [comment]
Thanks for reply, I also created the issue in mod repository:
https://github.com/spxctreofficial/enhancedcraft/issues/39

**Comment by lospejos** [comment]
I'm closing this issue, all further activity will be in related mod's issue: https://github.com/spxctreofficial/enhancedcraft/issues/39

**Comment by lospejos** [comment]
I'm closing this issue, all further activity will be in related mod's issue: https://github.com/spxctreofficial/enhancedcraft/issues/39
