### ISSUE TITLE
[1.18.2] Origins powers won't load on latest version of QFAPI/QSL

### ISSUE THREAD

**Issue by faeldray** [QuiltMC/quilted-fabric-api#36]
Default powers (or any powers for that matter) won't load when using QFAPI 1.0.0-beta.24 and QSL 1.1.0-beta.26. There's no crash report but the latest.log says that the powers are unregistered. However, if I downgrade to QSL 1.1.0-beta.19 and QFAPI 1.0.0-beta.22, there are no errors and the powers load properly.

[latest.log](https://gist.github.com/faeldray/1632672550dc0cd7af13014ddf8e56dc)

**Comment by LambdAurora** [comment]
This is due to apace100/calio#3.
[You can try to compile my fork](https://github.com/LambdAurora/calio-test) and put it into the mods folder to fix it.

**Comment by faeldray** [comment]
I'll give it a shot as soon as I figure out how to compile mods...

**Comment by faeldray** [comment]
@LambdAurora I compiled it and it looks like it does indeed fix the issue, so that's awesome. I'd like to do some more testing though.

**Comment by faeldray** [comment]
Everything looks like it's working great, thanks for the fix @LambdAurora
