### ISSUE TITLE
Balm crashes with some mods, specifically on Quilt

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilted-fabric-api#39]
**MC** 1.19.2
**QSL** 4.0.0-beta.12/13
**[Balm](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)** 4.5.2+0

To reproduce the crash, you will also need another mod, I personally tested it with [Terrestria](https://www.curseforge.com/minecraft/mc-mods/terrestria), but apparently [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric) causes the same crash: https://github.com/ModdingForBlockheads/Balm/issues/37.

The crash does not happen on Fabric. Initially reported to Terrestria, but according to them it's not an issue on their side: https://github.com/TerraformersMC/Terrestria/issues/278; also reported to Balm and was suggested to report to Quilt, as the crash is exclusive to Quilt: https://github.com/ModdingForBlockheads/Balm/issues/36.

Logs: https://gist.github.com/SplendidAlakey/dde2c2bdf95113aa01eb866725e0ee53

**Comment by lospejos** [comment]
I'm not sure but it seems that is the mod's issue rather than the Quilt issue. At least all such other cases was fixed by mod authors not by Quilt team, AFAIK.

**Comment by SplendidAlakey** [comment]
Sadly, the issue now started to affect the newest version of [ShetiPhianCore](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/4311851), as well: https://gist.github.com/SplendidAlakey/5b7c923fa2a882b124815df332cc84f3

**Comment by SplendidAlakey** [comment]
I'm closing this, because it's a loader issue, not QFAPI/QSL. Going to continue tracking the issue over at https://github.com/QuiltMC/quilt-loader/issues/129
