### ISSUE TITLE
QSL 4.0.0 beta 14 crashes on startup with some entity mods; creates log spam

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilted-fabric-api#40]
**MC** 1.19.2
**QSL** 4.0.0-beta.14
**[Creeper Overhaul](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)** 2.0.3
**[Llamarama](https://www.curseforge.com/minecraft/mc-mods/llamarama)** 1.8.4

To reproduce the crash:

1. Install QSL 4.0.0 beta 14
2. Install either Creeper Overhaul or Llamarama
3. Try to launch the game

Reporting here because the issue only started to happen after updating to beta 14, beta 13 works with no issues. I don't know of other affected mods, that add new mobs, but I tested it against a large modpack and these are the only 2 that I found to be broken on the newest QSL.

Logs: https://gist.github.com/Footage2-Amply-Pounce/582ad42e6d8a09bf5264d49f3b7f3f86 (only included the Creeper Overhaul crash, because Llamarama one looks identical, but let me know if you need that one too).

As for the log spam issue, for some reason this update started to spam the following message in the log: `[org.quiltmc.quilted_fabric_api.impl.content.registry.util.QuiltDeferringQueues] did this work?`. Could this be limited to just 1 message per launch? Not sure which mods cause this, let me know if it's important, I'll spend some time trying to narrow it down.

**Comment by LambdAurora** [comment]
```
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/DefaultAttributeRegistryAccessor
	at tech.thatgravyboat.creeperoverhaul.fabric.CreepersFabric.onInitialize(CreepersFabric.java:46)
```

Congrats on finding a mod that uses internal APIs while it shouldn't!
Please report this issue to Creeper Overhaul.

And as for the log spam issue, that might be a debug message that got accidentally left in.

**Comment by SplendidAlakey** [comment]
Please excuse me, if this is a dumb question, I'm a complete noob at this, but is this the same as fabric impl classes? I'm asking because Creeper Overhaul already had this issue before and the dev said they no longer use those. If it's not the same, then I'm afraid I'll just drop the mod, as the dev does not wish to explicitly support Quilt.

**Comment by LambdAurora** [comment]
It is the same as Fabric impl classes: Fabric API's mixins, even if they are accessors, are internal/impl code.

**Comment by SplendidAlakey** [comment]
Got it, thank you. I will report it to both mods, and hopefully they fix it :) You can close this issue, otherwise I'll keep it open for visibility.

**Comment by EnnuiL** [comment]
So,
1) Creeper Overhaul is using implementation details when they really shouldn't (it being an internal accessor mixin when there's literally an API that does it for them); That's only Creeper Overhaul though, because I don't see any evidence of shenanigans inside Llamarama's source code; Are you sure it's the same issue?
2) ...heck, that's the debug message that was meant to test a workaround for mods that register blocks with unregistered items in the content registries

Anyway, if the situation in 1) turns out to be worse with many mods committing this violation, I'll reintroduce the accessor for compatibility reasons, but if it's an isolated case? They should fix it, because Fabric API can also decide to remove/move around implementation details too; As for 2)? yep... my mistake; It should be fixed on the next QFAPI update

**Comment by SplendidAlakey** [comment]
> 1. because I don't see any evidence of shenanigans inside Llamarama's source code; Are you sure it's the same issue?

No, not sure, just what I assumed based on the logs, they seemed identical. Also both mods add/modify mobs. Here are Llamarama logs: https://gist.github.com/Footage2-Amply-Pounce/83b853c38d80849e558e20249520c46d. I also opened an issue on their side. Not going to open on Creeper Overhaul's, because I see that ~~you~~ wafflecoffee already made a pull request for them, thanks!

And yeah, this is definitely an isolated issue. I have a modpack consisting of nearly 500 mods and only these 2 caused the crash, so, IMO, you should keep whatever changes you made.

**Comment by EnnuiL** [comment]
oh no, the Llamarama issue is actually an issue with our bridge, not their fault; Yep, expect a new QFAPI update soonish

**Comment by SplendidAlakey** [comment]
~~Oops, should I close the issue on their side?~~

Closed on their side.

**Comment by EnnuiL** [comment]
So, with QFAPI 4.0.0-beta.15:
 - Creeper Overhaul's issue should be fixed on their side
 - Llamarama has been fixed on our side
 - The debug message has been removed
 
 So, yeah, I'm marking this as fixed
