### ISSUE TITLE
Quilt specific 4-way crash between Earth2Java, Enchancement, KubeJS and Frame API

### ISSUE THREAD

**Issue by SplendidAlakey** [QuiltMC/quilted-fabric-api#42]
**MC** 1.19.2
**QFAPI** 4.0.0-beta.17
**[Earth2Java](https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric/files/3968924)** 1.9.3
**[Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement/files/4021077)** 5
**[KubeJS](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4053874)** 1902.6.0-build.101
**[Frame API](https://www.curseforge.com/minecraft/mc-mods/frame-api/files/3943404)** 0.26.1

To reproduce simply install all 4 mods and all their dependencies, then try to launch the game. The crash doesn't happen on Fabric with identical mods.

Logs: https://gist.github.com/SplendidAlakey/0fec210ea1df4ced214d472fdaee6baf

Already talked about it on Discord a bit, but making an issue here to keep track of. Let me know if I need to report this to the mod devs instead.

**Comment by lukebemish** [comment]
Enhancement is mixing in to an internal class of Architectury API: <https://github.com/MoriyaShiine/enchancement/blob/a20391d824e834bd4f4222d2c91977f5579a553b/src/main/java/moriyashiine/enchancement/mixin/vanillachanges/disabledisallowedenchantments/integration/architectury/RegistriesImplRegistartImplMixin.java>

As you likely have architectury API for quilt installed, this just does not work. I'd open an issue on their (enhancement's) repo.

**Comment by lukebemish** [comment]
Wait, I may be mistaken. That seems to be a *related* issue, but not the root cause, since architectury is just the fabric version at present

**Comment by SplendidAlakey** [comment]
Enchancement was the mod that made me discover the crash and, yeah, I noticed that Architectury was somehow mixed in, but since it's a Quilt exclusive crash, I decided to report here first.

As for Architectury only having just the Fabric version, they formally support both in 1 jar:
![image](https://user-images.githubusercontent.com/86702831/198912627-134b43f2-7d6d-47a5-84f1-7239b66f2c46.png)

**Comment by lukebemish** [comment]
Yes, that's what I mean; they don't have 2 separate versions. I'm pretty sure whatever is going on here is wrapped up in that re-entrance error. I'll see what I can figure out

**Comment by SplendidAlakey** [comment]
No longer an issue with the latest versions of all mods + Quilt loader 0.17.7 and 0.18.x. No idea what fixed it.
