### ISSUE TITLE
Tackle down issues involving Machete and Gradle 8.0-incompatible shenanigans

### ISSUE THREAD

**Issue by EnnuiL** [QuiltMC/quilted-fabric-api#47]
It's beginning to pollute the buildscript too much and it's becoming unworkaroundable; It's not a fatal error, at least until Gradle 8.0 happens, but it's important to get this fixed

**Comment by EnnuiL** [comment]
With Gradle 8.0's release happening recently, something needs to be done, although it'll likely be only solvable on the plugin's side

**Comment by eristhea** [comment]
fixed with #98

**Comment by eristhea** [comment]
didn't mean to close, just to mention it
whoops
