### ISSUE TITLE
[1.19.2] QSL Doesn't Provide FAPI 0.71, but Modern Industrialization Requires It

### ISSUE THREAD

**Issue by Mg138** [QuiltMC/quilted-fabric-api#58]
Modern Industrialization recently bumped the FAPI requirement to 0.71, but QSL only has FAPI 0.71 on 1.19.3.

We tried to build QSL ourselves targeting 1.19.2 and providing FAPI 0.71, but that didn't work out.

Is there any (temporary) solution for this? Or do we simply need to wait until everyone is up with 1.19.3?

CC: @Technici4n (@AztechMC ?) Is there anything strictly required from FAPI 0.71?

**Comment by EnnuiL** [comment]
A 1.19.2 update based on Fabric API 0.72.0 is coming soon, with the 1.19.3 counterpart being ready today; While the latest Quilt Loader 0.18.1 betas do support dependency overrides, considering Tech's status as a Fabric API developer, I have a feeling that the bumping of the minimum version was warranted;

I try to support both versions to the best of my capabilities, but yeah, scheduling these alongside QSL updates and personal projects does mean that I may take longer than usual for an update; But yeah, don't worry, QSL/QFAPI 1.19.2 isn't being abandoned and won't be any time soon :P

**Comment by Mg138** [comment]
Closing this, thank you for the input!
