### ISSUE TITLE
Fapi needs updated to 0.14.12

### ISSUE THREAD

**Issue by Nathan22211** [QuiltMC/quilted-fabric-api#61]
quite a few mods for 1.19.3 rely on that version of Fabric API, but at current this only makes 1.19.2 mods a guarantee for 1.19.3, which isn't possible as I think there were breaking changes between 1.19.2 and 1.19.3. One example is darkhax's openloader

**Comment by Jamalam360** [comment]
First of all, 0.14.12 is a Fabric Loader version rather than Fabric API, and second 0.14.12 is supported by the latest Quilt Loader beta (not the 0.18.1 betas I think, the 0.17.something beta)

**Comment by EnnuiL** [comment]
Yes, this isn't a Quilted Fabric API issue, it's a Quilt Loader one; However, Quilt Loader 0.17.10 and the latest 0.18.1 beta have addressed this by supporting Fabric Loader 0.14.13
