### ISSUE TITLE
test server does not stop itself

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/quilted-fabric-api#78]
when running the `Game Test` task in intellij, the test server never stops. yes I learned this the hard way. it should probably stop after 1000 ticks or so.

**Comment by EnnuiL** [comment]
Turns out I fixed it during [this commit](https://github.com/QuiltMC/quilted-fabric-api/commit/d96978eecda37f40cf411deb54023524689f713d)! It was caused by uh, a duplication of `-D`s happening, resulting into `-D-Dquilt.game_test=true`;
