### ISSUE TITLE
Can't connect to a server

### ISSUE THREAD

**Issue by stantios** [QuiltMC/quilted-fabric-api#82]
QFAPI / QSL Version: QFAPI 4.0.0-beta.28 and QSL 3.0.0-beta.29
Log: https://mclo.gs/ambk4hB

Description: I tried to join this whitelisted server that supports both 1.19.3 and 1.19.2 clients with the mods that I play and then I get an error message (shown in screenshots). I went through my mods list and found that this only happens when QFAPI / QSL is enabled, as when I have no mods in my instance / folder with just Quilt Loader 0.18.2, I can connect to the server with no issues

Screenshots: 
![image](https://user-images.githubusercontent.com/98621617/221431004-04201b51-4e27-4bf4-a4fd-7ed1abf58c30.png)

**Comment by eristhea** [comment]
this is not a qfapi issue, the registry is mismatched
```
[19:30:05] [Netty Client IO #1/WARN]: Missing entries for registry "minecraft:entity_type":
- minecraft:camel
- polysit:seat
```

**Comment by stantios** [comment]
So, this is an issue with the server?

**Comment by eristhea** [comment]
it could be. could you try connecting from 1.19.3? that will solve the `minecraft:camel` issue, and possibly the polysit issue with it.

**Comment by stantios** [comment]
Joining with 1.19.3 solves the issue but that's expected since the server itself is 1.19.3 and has ViaFabric to allow older versions to join the server.

**Comment by stantios** [comment]
Also, this doesn't happen when only having Fabric Loader and Fabric API.

**Comment by eristhea** [comment]
Strange, I'll look into this when I have time

**Comment by stantios** [comment]
This could be an issue with QSL as I think uses a different a registry system to match mods whereas Fabric doesn't really care at all.

**Comment by codegoose** [comment]
I had this issue yesterday. I was able to get past it by copying the config folder from the client to the server. My thought was to ensure that both folders had exactly the same content.

Is Quilt just checking all the files in that folder for the same hash or is it more complex?

**Comment by stantios** [comment]
> This could be an issue with QSL as I think uses a different a registry system to match mods whereas Fabric doesn't really care at all.

I think it has something to with this so I think it's a QSL issue, I'm going to close this and reopen it on the QSL Github.
