### ISSUE TITLE
Error starting up quilt!

### ISSUE THREAD

**Issue by spacesixty** [QuiltMC/quilted-fabric-api#89]
[crash-2023-03-24_01.16.40.6414-quilt_loader.txt](https://github.com/QuiltMC/quilted-fabric-api/files/11065844/crash-2023-03-24_01.16.40.6414-quilt_loader.txt)

Hi, I just recently migrated over from fabric and wanted to know what was causing this error as many others ive asked in other discords dont know and my application is currently under review for the discord server, thank you! There are fabric mods on there but from looking it up they should work with quilt but idk fully sorry for the pain!

**Comment by SplendidAlakey** [comment]
Hey, I already replied to you on the forums, but it's most likely just Decorative Blocks causing the crash, as it's incompatible with Quilt.

**Comment by eristhea** [comment]
for a bit of extra information, refer to https://github.com/lilypuree/Decorative-Blocks/issues/76
this is on the mod's side

**Comment by spacesixty** [comment]
[latest.log](https://github.com/QuiltMC/quilted-fabric-api/files/11240693/latest.log)

Hi there sorry for the late response but I tried to remove it and now it crashes on startup with this log being the only thing coming out

**Comment by Platymemo** [comment]
It's an incompatibility with Combat Enchants. See https://github.com/dsfhdshdjtsb/enchantments/issues/21

**Comment by spacesixty** [comment]
Ahhh I see, I also got this log if it helps at all
[crash-2023-04-15_14.47.42.7315-quilt_loader.txt](https://github.com/QuiltMC/quilted-fabric-api/files/11240741/crash-2023-04-15_14.47.42.7315-quilt_loader.txt)

**Comment by spacesixty** [comment]
[latest.log](https://github.com/QuiltMC/quilted-fabric-api/files/11240758/latest.log)

And now its no longer giving me a crash report its just giving me a log
