### ISSUE TITLE
quilted fabric object builder api missing getMaterial()

### ISSUE THREAD

**Issue by JieningYu** [QuiltMC/quilted-fabric-api#9]
[issue with eden ring](https://github.com/paulevsGitch/EdenRing/issues/27)
missing `net.fabricmc.fabric.mixin.object.builder.AbstractBlockSettingsAccessor.getMaterial()`

**Comment by triphora** [comment]
This is really an issue with Eden Ring -- there is no reason that it should be using a Fabric API mixin class, especially not an accessor, it should just be accessing it through its own accessor. We only support API classes and some commonly used impl classes.

**Comment by triphora** [comment]
Nevermind -- as it turns out, this is *kind of* used as public API, so I'll be making something here soon to readd these methods
