### ISSUE TITLE
Mod data not loading when using Quilt

### ISSUE THREAD

**Issue by ejektaflex** [QuiltMC/quilted-fabric-api#92]
Hi - I had a user report that when using my mod, data from `resources/data` related to my mod does not seem to load. Since what I've read seems to indicate that you're doing a re-implementation of FAPI and the data loading process relies on FAPI to work, I figure that this is the place to report it.

Here is the repository for my mod:
https://github.com/ejektaflex/Bountiful

Here is my data load method:
https://github.com/ejektaflex/Bountiful/blob/1.19.4/common/src/main/java/io/ejekta/bountiful/config/ResourceLoadStrategy.kt#L49

And here is where I add the event listener:
https://github.com/ejektaflex/Bountiful/blob/1.19.4/fabric/src/main/java/io/ejekta/bountiful/BountifulModFabric.kt#L60

This works with Fabric, but fails to load with Quilt. This is using Fabric API 0.76.0+1.19.4.

**Comment by TheGlitch76** [comment]
Everything seems to be looking fine to me:
![image](https://user-images.githubusercontent.com/19521552/232541208-d2971c9a-f4d8-44fe-9fe5-b6eb073bf48d.png)
I was able to submit bounties and get rewards without issues.
But i don't know what I'm looking for. Can you provide steps to reproduce and tell what to look for?

**Comment by ejektaflex** [comment]
Well, I'll tell them that it can't be reproduced. If it comes up again, I'll try to look into it a bit further. Thanks!
