### ISSUE TITLE
Error launching in 1.19.4

### ISSUE THREAD

**Issue by AliahX** [QuiltMC/quilted-fabric-api#94]
I'm not able to start the game, as it just reaches the red screen without a logo or loading bar and then crashes. I am using no mods apart from qfapi-6.0.0-beta.3_qsl-5.0.0-beta.2_fapi-0.76.0_mc-1.19.4 and loader version 0.18.9-1.19.4

[crash-2023-04-13_18.28.21-client.txt](https://github.com/QuiltMC/quilted-fabric-api/files/11218826/crash-2023-04-13_18.28.21-client.txt)

**Comment by eristhea** [comment]
hi, two things!
1. please ask about issues like this on the [forum](https://forum.quiltmc.org) or the [discord](https://https://discord.com/invite/M7GpuyTBvy) first. this issue tracker is meant for fixable incompatibilities and issues with mods, or issues with qfapi itself, not to be a help center.
2. before you go and post in the forum, it seems like you've attached the wrong crash report, that one is chock-full of mods
