### ISSUE TITLE
Missing Deprecation on FAPI's Armor Rendering API

### ISSUE THREAD

**Issue by ChampionAsh5357** [QuiltMC/quilted-fabric-api#99]
There is a missing deprecation on FAPI's `ArmorRenderer` with introduction of QFAPI's Armor Rendering logic from QuiltMC/quilt-standard-libraries#166.

In general, this could be a master issue for all missing deprecations, but it would probably just be easier to track by logging which PRs were merged and just do it in batches every so often. This is mainly so that there isn't one perpetually open issue until Quilt eventually stops using Fabric.

**Comment by EnnuiL** [comment]
Solved on QFAPI v6.0.0-beta.8 and v7.0.0-alpha.2; While I appreciate the intention of having a megaissue of some sorts, I'd rather have individual ones come as more APIs are superseded, or rather, I'd rather not forget to add those myself :p
